name: nlp-env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.41.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.2
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pyzmq=27.0.2
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - blis==1.3.0
      - catalogue==2.0.10
      - catboost==1.2.8
      - category-encoders==2.6.4
      - certifi==2025.7.9
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpathlib==0.22.0
      - confection==0.1.5
      - contourpy==1.3.0
      - cramjam==2.11.0
      - cycler==0.12.1
      - cymem==2.0.11
      - fastai==2.7.19
      - fastcore==1.7.29
      - fastdownload==0.0.7
      - fastparquet==2024.11.0
      - fastprogress==1.0.3
      - filelock==3.18.0
      - fonttools==4.59.2
      - fsspec==2025.5.1
      - graphviz==0.21
      - idna==3.10
      - imbalanced-learn==0.12.4
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - language-data==1.3.0
      - lightgbm==4.6.0
      - llvmlite==0.43.0
      - marisa-trie==1.3.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mpmath==1.3.0
      - murmurhash==1.0.13
      - narwhals==2.8.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.3.1
      - patsy==1.0.1
      - pillow==11.3.0
      - plotly==6.3.1
      - preshed==3.0.10
      - pyarrow==21.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyod==2.0.5
      - pyparsing==3.2.4
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - rich==14.1.0
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - shellingham==1.5.4
      - smart-open==7.3.1
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - statsmodels==0.14.5
      - sympy==1.13.1
      - thinc==8.3.6
      - threadpoolctl==3.6.0
      - torch==2.4.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - triton==3.0.0
      - typer==0.17.4
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==1.17.3
      - xgboost==2.1.4
